# Generated by Django 5.2.8 on 2025-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('prenom', models.CharField(max_length=100, verbose_name='اللقب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('telephone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
    ]
