# Generated by Django 5.2.8 on 2025-11-29 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(db_index=True, max_length=100, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[+]?[0-9\\s-()]+$', 'Format de téléphone invalide')], verbose_name='رقم الهاتف'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom', 'prenom'], name='clients_cli_nom_f99d14_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
    ]
