# Generated by Django 5.2.8 on 2025-11-29 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_category_produit_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom', 'category'], name='produits_pr_nom_b0cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['quantite'], name='produits_pr_quantit_b4e995_idx'),
        ),
    ]
