# Generated by Django 4.2.16 on 2025-11-30 09:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_options_produit_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[utils.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
